# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AreaLimiter
                                 A QGIS plugin
 Keeps polygons within a target area
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-18
        copyright            : (C) 2025 by Jessie Lindsay
        email                : jessie.lindsay42@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AreaLimiter class from file AreaLimiter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .arealimiter import AreaLimiter
    return AreaLimiter(iface)
