# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arealimiter_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AreaLimiterDockWidgetBase(object):
    def setupUi(self, AreaLimiterDockWidgetBase):
        AreaLimiterDockWidgetBase.setObjectName("AreaLimiterDockWidgetBase")
        AreaLimiterDockWidgetBase.resize(562, 200)
        self.dockContents = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.dockContents.setFont(font)
        self.dockContents.setObjectName("dockContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockContents)
        self.gridLayout.setObjectName("gridLayout")
        self.labelStatus = QtWidgets.QLabel(self.dockContents)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout.addWidget(self.labelStatus, 1, 0, 1, 1)
        self.spinTargetArea = QtWidgets.QDoubleSpinBox(self.dockContents)
        self.spinTargetArea.setMinimum(0.01)
        self.spinTargetArea.setMaximum(100000.0)
        self.spinTargetArea.setObjectName("spinTargetArea")
        self.gridLayout.addWidget(self.spinTargetArea, 2, 0, 1, 1)
        self.btnApply = QtWidgets.QPushButton(self.dockContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.btnApply.setFont(font)
        self.btnApply.setObjectName("btnApply")
        self.gridLayout.addWidget(self.btnApply, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.dockContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnEditSelected = QtWidgets.QPushButton(self.dockContents)
        self.btnEditSelected.setObjectName("btnEditSelected")
        self.gridLayout.addWidget(self.btnEditSelected, 4, 1, 1, 1)
        self.comboLayer = QtWidgets.QComboBox(self.dockContents)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.comboLayer.setFont(font)
        self.comboLayer.setEditable(True)
        self.comboLayer.setObjectName("comboLayer")
        self.gridLayout.addWidget(self.comboLayer, 0, 1, 1, 1)
        self.comboUnits = QtWidgets.QComboBox(self.dockContents)
        self.comboUnits.setObjectName("comboUnits")
        self.comboUnits.addItem("")
        self.comboUnits.addItem("")
        self.gridLayout.addWidget(self.comboUnits, 3, 0, 1, 1)
        AreaLimiterDockWidgetBase.setWidget(self.dockContents)

        self.retranslateUi(AreaLimiterDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(AreaLimiterDockWidgetBase)

    def retranslateUi(self, AreaLimiterDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        AreaLimiterDockWidgetBase.setWindowTitle(_translate("AreaLimiterDockWidgetBase", "AreaLimiter"))
        self.labelStatus.setText(_translate("AreaLimiterDockWidgetBase", "Current area:"))
        self.btnApply.setText(_translate("AreaLimiterDockWidgetBase", "Create new polygon"))
        self.label.setText(_translate("AreaLimiterDockWidgetBase", "Select polygon layer"))
        self.btnEditSelected.setText(_translate("AreaLimiterDockWidgetBase", "Edit selected"))
        self.comboUnits.setItemText(0, _translate("AreaLimiterDockWidgetBase", "m²"))
        self.comboUnits.setItemText(1, _translate("AreaLimiterDockWidgetBase", "ha"))
